const CONTENT={
  units:[
    {id:1,name:'初次见面',progress:0,words:[{en:'Excuse',zh:'对不起',ph:'/ɪkˈskjuːz/',ex:'Excuse me.'},{en:'Yes',zh:'是的',ph:'/jes/',ex:'Yes, it is.'},{en:'Pardon',zh:'原谅',ph:'/ˈpɑːrdn/',ex:'I beg your pardon.'},{en:'Thank',zh:'谢谢',ph:'/θæŋk/',ex:'Thank you very much.'},{en:'Please',zh:'请',ph:'/pliːz/',ex:'Please sit down.'},{en:'Handbag',zh:'手提包',ph:'/ˈhændbæɡ/',ex:'Is this your handbag?'},{en:'Pen',zh:'钢笔',ph:'/pen/',ex:'This is my pen.'},{en:'Pencil',zh:'铅笔',ph:'/ˈpensl/',ex:'Give me a pencil.'},{en:'Book',zh:'书',ph:'/bʊk/',ex:'Read your book.'},{en:'Watch',zh:'手表',ph:'/wɒtʃ/',ex:'That is a watch.'},{en:'Coat',zh:'外套',ph:'/koʊt/',ex:'My coat is blue.'},{en:'Dress',zh:'连衣裙',ph:'/dres/',ex:'Your dress is lovely.'},{en:'Skirt',zh:'裙子',ph:'/skɜːrt/',ex:'She wears a skirt.'},{en:'Shirt',zh:'衬衫',ph:'/ʃɜːrt/',ex:'His shirt is white.'},{en:'Car',zh:'汽车',ph:'/kɑːr/',ex:'The car is new.'},{en:'House',zh:'房子',ph:'/haʊs/',ex:'This is a house.'},{en:'Umbrella',zh:'雨伞',ph:'/ʌmˈbrelə/',ex:'Take your umbrella.'},{en:'Ticket',zh:'票',ph:'/ˈtɪkɪt/',ex:'Here is your ticket.'},{en:'Suit',zh:'套装',ph:'/suːt/',ex:'Your suit is smart.'},{en:'School',zh:'学校',ph:'/skuːl/',ex:'Go to school.'},{en:'Teacher',zh:'老师',ph:'/ˈtiːtʃər/',ex:'She is a teacher.'},{en:'Son',zh:'儿子',ph:'/sʌn/',ex:'My son is tall.'},{en:'Daughter',zh:'女儿',ph:'/ˈdɔːtər/',ex:'Her daughter is young.'},{en:'Morning',zh:'早晨',ph:'/ˈmɔːrnɪŋ/',ex:'Good morning.'},{en:'Nice',zh:'好的',ph:'/naɪs/',ex:'Nice to meet you.'},{en:'Meet',zh:'遇见',ph:'/miːt/',ex:'Nice to meet you.'},{en:'Sir',zh:'先生',ph:'/sɜːr/',ex:'Thank you, sir.'},{en:'Here',zh:'这里',ph:'/hɪər/',ex:'Here you are.'}]},
    {id:2,name:'物品颜色',progress:0,words:[{en:'Hello',zh:'你好',ph:'/həˈloʊ/',ex:'Hello, everyone.'},{en:'Today',zh:'今天',ph:'/təˈdeɪ/',ex:'How are you today?'},{en:'Well',zh:'好地',ph:'/wel/',ex:'I am very well.'},{en:'Fine',zh:'好的',ph:'/faɪn/',ex:'I am fine.'},{en:'Goodbye',zh:'再见',ph:'/ɡʊdˈbaɪ/',ex:'Goodbye, see you.'},{en:'Colour',zh:'颜色',ph:'/ˈkʌlər/',ex:'What colour is it?'},{en:'Green',zh:'绿色',ph:'/ɡriːn/',ex:'The grass is green.'},{en:'Blue',zh:'蓝色',ph:'/bluː/',ex:'The sky is blue.'},{en:'White',zh:'白色',ph:'/waɪt/',ex:'Snow is white.'},{en:'Black',zh:'黑色',ph:'/blæk/',ex:'My shoes are black.'},{en:'Yellow',zh:'黄色',ph:'/ˈjeloʊ/',ex:'The sun is yellow.'},{en:'Orange',zh:'橙色',ph:'/ˈɔːrɪndʒ/',ex:'The orange is orange.'},{en:'Brown',zh:'棕色',ph:'/braʊn/',ex:'His eyes are brown.'},{en:'Red',zh:'红色',ph:'/red/',ex:'The rose is red.'},{en:'New',zh:'新的',ph:'/njuː/',ex:'My car is new.'},{en:'Old',zh:'旧的',ph:'/oʊld/',ex:'This house is old.'},{en:'Big',zh:'大的',ph:'/bɪɡ/',ex:'The box is big.'},{en:'Small',zh:'小的',ph:'/smɔːl/',ex:'The cat is small.'},{en:'Fat',zh:'胖的',ph:'/fæt/',ex:'The dog is fat.'},{en:'Thin',zh:'瘦的',ph:'/θɪn/',ex:'She is thin.'},{en:'Tall',zh:'高的',ph:'/tɔːl/',ex:'He is very tall.'},{en:'Short',zh:'矮的',ph:'/ʃɔːrt/',ex:'She is short.'},{en:'Young',zh:'年轻的',ph:'/jʌŋ/',ex:'She is young.'},{en:'Clean',zh:'干净的',ph:'/kliːn/',ex:'The room is clean.'},{en:'Dirty',zh:'脏的',ph:'/ˈdɜːrti/',ex:'Your hands are dirty.'},{en:'Hot',zh:'热的',ph:'/hɒt/',ex:'The coffee is hot.'},{en:'Cold',zh:'冷的',ph:'/koʊld/',ex:'The water is cold.'},{en:'Shoes',zh:'鞋子',ph:'/ʃuːz/',ex:'Your shoes are nice.'}]},
    {id:3,name:'日常起居',progress:0,words:[{en:'Come',zh:'来',ph:'/kʌm/',ex:'Come here, please.'},{en:'Go',zh:'去',ph:'/ɡoʊ/',ex:'Go upstairs.'},{en:'Sit',zh:'坐',ph:'/sɪt/',ex:'Sit down, please.'},{en:'Stand',zh:'站',ph:'/stænd/',ex:'Stand up, please.'},{en:'Open',zh:'打开',ph:'/ˈoʊpən/',ex:'Open the door.'},{en:'Close',zh:'关上',ph:'/kloʊz/',ex:'Close the window.'},{en:'Door',zh:'门',ph:'/dɔːr/',ex:'Open the door.'},{en:'Window',zh:'窗户',ph:'/ˈwɪndoʊ/',ex:'The window is clean.'},{en:'Bedroom',zh:'卧室',ph:'/ˈbedruːm/',ex:'This is my bedroom.'},{en:'Bathroom',zh:'浴室',ph:'/ˈbæθruːm/',ex:'The bathroom is small.'},{en:'Kitchen',zh:'厨房',ph:'/ˈkɪtʃɪn/',ex:'She is in the kitchen.'},{en:'Garden',zh:'花园',ph:'/ˈɡɑːrdn/',ex:'The garden is lovely.'},{en:'Room',zh:'房间',ph:'/ruːm/',ex:'The room is big.'},{en:'Table',zh:'桌子',ph:'/ˈteɪbl/',ex:'The book is on the table.'},{en:'Chair',zh:'椅子',ph:'/tʃeər/',ex:'Sit on the chair.'},{en:'Bed',zh:'床',ph:'/bed/',ex:'The bed is soft.'},{en:'Cup',zh:'杯子',ph:'/kʌp/',ex:'A cup of tea.'},{en:'Glass',zh:'玻璃杯',ph:'/ɡlæs/',ex:'A glass of water.'},{en:'Plate',zh:'盘子',ph:'/pleɪt/',ex:'The plate is clean.'},{en:'Box',zh:'盒子',ph:'/bɒks/',ex:'The box is empty.'},{en:'Cigarette',zh:'香烟',ph:'/ˌsɪɡəˈret/',ex:'Give me a cigarette.'},{en:'Television',zh:'电视',ph:'/ˈtelɪvɪʒn/',ex:'Turn on the television.'},{en:'Radio',zh:'收音机',ph:'/ˈreɪdioʊ/',ex:'Listen to the radio.'},{en:'Newspaper',zh:'报纸',ph:'/ˈnjuːzpeɪpər/',ex:'Read the newspaper.'},{en:'Empty',zh:'空的',ph:'/ˈempti/',ex:'The box is empty.'},{en:'Full',zh:'满的',ph:'/fʊl/',ex:'The glass is full.'},{en:'Large',zh:'大的',ph:'/lɑːrdʒ/',ex:'A large room.'},{en:'Little',zh:'小的',ph:'/ˈlɪtl/',ex:'A little girl.'}]},
    {id:4,name:'家务物品',progress:0,words:[{en:'Refrigerator',zh:'冰箱',ph:'/rɪˈfrɪdʒəreɪtər/',ex:'Open the refrigerator.'},{en:'Electric',zh:'电的',ph:'/ɪˈlektrɪk/',ex:'An electric cooker.'},{en:'Cooker',zh:'炉灶',ph:'/ˈkʊkər/',ex:'The cooker is new.'},{en:'Cupboard',zh:'碗柜',ph:'/ˈkʌbərd/',ex:'Put it in the cupboard.'},{en:'Picture',zh:'图画',ph:'/ˈpɪktʃər/',ex:'The picture is on the wall.'},{en:'Wall',zh:'墙',ph:'/wɔːl/',ex:'The wall is white.'},{en:'Floor',zh:'地板',ph:'/flɔːr/',ex:'The floor is clean.'},{en:'Lamp',zh:'灯',ph:'/læmp/',ex:'Turn on the lamp.'},{en:'Desk',zh:'书桌',ph:'/desk/',ex:'The book is on the desk.'},{en:'Shelf',zh:'架子',ph:'/ʃelf/',ex:'Put it on the shelf.'},{en:'Knife',zh:'刀',ph:'/naɪf/',ex:'The knife is sharp.'},{en:'Fork',zh:'叉子',ph:'/fɔːrk/',ex:'Give me a fork.'},{en:'Spoon',zh:'勺子',ph:'/spuːn/',ex:'The spoon is dirty.'},{en:'Bottle',zh:'瓶子',ph:'/ˈbɒtl/',ex:'A bottle of milk.'},{en:'Tin',zh:'罐头',ph:'/tɪn/',ex:'A tin of beans.'},{en:'Sharp',zh:'锋利的',ph:'/ʃɑːrp/',ex:'The knife is sharp.'},{en:'Blunt',zh:'钝的',ph:'/blʌnt/',ex:'The pencil is blunt.'},{en:'Soft',zh:'软的',ph:'/sɒft/',ex:'The bed is soft.'},{en:'Hard',zh:'硬的',ph:'/hɑːrd/',ex:'The table is hard.'},{en:'Sweet',zh:'甜的',ph:'/swiːt/',ex:'The candy is sweet.'},{en:'Sour',zh:'酸的',ph:'/ˈsaʊər/',ex:'The lemon is sour.'},{en:'Carpet',zh:'地毯',ph:'/ˈkɑːrpɪt/',ex:'The carpet is red.'},{en:'Saucer',zh:'茶托',ph:'/ˈsɔːsər/',ex:'A cup and saucer.'},{en:'Teapot',zh:'茶壶',ph:'/ˈtiːpɒt/',ex:'The teapot is on the table.'},{en:'Case',zh:'箱子',ph:'/keɪs/',ex:'This is your case.'},{en:'Hat',zh:'帽子',ph:'/hæt/',ex:'Your hat is lovely.'},{en:'Dresser',zh:'梳妆台',ph:'/ˈdresər/',ex:'The dresser is in the bedroom.'},{en:'Trousers',zh:'裤子',ph:'/ˈtraʊzərz/',ex:'My trousers are new.'}]},
    {id:5,name:'天气行动',progress:0,words:[{en:'Cloud',zh:'云',ph:'/klaʊd/',ex:'The cloud is white.'},{en:'Sky',zh:'天空',ph:'/skaɪ/',ex:'The sky is blue.'},{en:'Sun',zh:'太阳',ph:'/sʌn/',ex:'The sun is hot.'},{en:'Shine',zh:'照耀',ph:'/ʃaɪn/',ex:'The sun is shining.'},{en:'Rain',zh:'雨',ph:'/reɪn/',ex:'It is raining.'},{en:'Snow',zh:'雪',ph:'/snoʊ/',ex:'It is snowing.'},{en:'Wind',zh:'风',ph:'/wɪnd/',ex:'The wind is strong.'},{en:'Weather',zh:'天气',ph:'/ˈweðər/',ex:'The weather is nice.'},{en:'Walk',zh:'步行',ph:'/wɔːk/',ex:'Walk across the street.'},{en:'Run',zh:'跑',ph:'/rʌn/',ex:'He runs fast.'},{en:'Jump',zh:'跳',ph:'/dʒʌmp/',ex:'Jump up and down.'},{en:'Fly',zh:'飞',ph:'/flaɪ/',ex:'The bird flies.'},{en:'Sleep',zh:'睡觉',ph:'/sliːp/',ex:'Sleep well.'},{en:'Wash',zh:'洗',ph:'/wɒʃ/',ex:'Wash your hands.'},{en:'Cook',zh:'做饭',ph:'/kʊk/',ex:'She cooks dinner.'},{en:'Drink',zh:'喝',ph:'/drɪŋk/',ex:'Drink some water.'},{en:'Eat',zh:'吃',ph:'/iːt/',ex:'Eat your food.'},{en:'Put',zh:'放',ph:'/pʊt/',ex:'Put on your coat.'},{en:'Take',zh:'拿',ph:'/teɪk/',ex:'Take off your shoes.'},{en:'Turn',zh:'转动',ph:'/tɜːrn/',ex:'Turn left.'},{en:'Over',zh:'在上面',ph:'/ˈoʊvər/',ex:'Jump over the wall.'},{en:'Between',zh:'在…之间',ph:'/bɪˈtwiːn/',ex:'Sit between us.'},{en:'Across',zh:'穿过',ph:'/əˈkrɒs/',ex:'Walk across the road.'},{en:'Under',zh:'在…下面',ph:'/ˈʌndər/',ex:'The cat is under the table.'},{en:'Near',zh:'在…附近',ph:'/nɪr/',ex:'The school is near.'},{en:'Behind',zh:'在…后面',ph:'/bɪˈhaɪnd/',ex:'The dog is behind the door.'},{en:'In',zh:'在…里',ph:'/ɪn/',ex:'It is in the box.'},{en:'On',zh:'在…上',ph:'/ɒn/',ex:'The book is on the desk.'}]},
    {id:6,name:'食物餐饮',progress:0,words:[{en:'Bread',zh:'面包',ph:'/bred/',ex:'I eat bread for breakfast.'},{en:'Cheese',zh:'奶酪',ph:'/tʃiːz/',ex:'Do you like cheese?'},{en:'Egg',zh:'鸡蛋',ph:'/eɡ/',ex:'I have an egg.'},{en:'Butter',zh:'黄油',ph:'/ˈbʌtər/',ex:'Pass me the butter.'},{en:'Sugar',zh:'糖',ph:'/ˈʃʊɡər/',ex:'Do you want sugar?'},{en:'Coffee',zh:'咖啡',ph:'/ˈkɒfi/',ex:'A cup of coffee.'},{en:'Tea',zh:'茶',ph:'/tiː/',ex:'Would you like tea?'},{en:'Milk',zh:'牛奶',ph:'/mɪlk/',ex:'Drink your milk.'},{en:'Water',zh:'水',ph:'/ˈwɔːtər/',ex:'Give me some water.'},{en:'Juice',zh:'果汁',ph:'/dʒuːs/',ex:'Orange juice, please.'},{en:'Meat',zh:'肉',ph:'/miːt/',ex:'The meat is good.'},{en:'Chicken',zh:'鸡肉',ph:'/ˈtʃɪkɪn/',ex:'I like chicken.'},{en:'Fish',zh:'鱼',ph:'/fɪʃ/',ex:'The fish is fresh.'},{en:'Rice',zh:'米饭',ph:'/raɪs/',ex:'We eat rice for lunch.'},{en:'Potato',zh:'土豆',ph:'/pəˈteɪtoʊ/',ex:'Potatoes are cheap.'},{en:'Vegetable',zh:'蔬菜',ph:'/ˈvedʒtəbl/',ex:'Eat your vegetables.'},{en:'Fruit',zh:'水果',ph:'/fruːt/',ex:'Fruit is healthy.'},{en:'Apple',zh:'苹果',ph:'/ˈæpl/',ex:'An apple a day.'},{en:'Banana',zh:'香蕉',ph:'/bəˈnænə/',ex:'The banana is yellow.'},{en:'Orange',zh:'橙子',ph:'/ˈɔːrɪndʒ/',ex:'This orange is sweet.'},{en:'Lemon',zh:'柠檬',ph:'/ˈlemən/',ex:'The lemon is sour.'},{en:'Breakfast',zh:'早餐',ph:'/ˈbrekfəst/',ex:'Breakfast is ready.'},{en:'Lunch',zh:'午餐',ph:'/lʌntʃ/',ex:'We have lunch at noon.'},{en:'Dinner',zh:'晚餐',ph:'/ˈdɪnər/',ex:'Dinner is at six.'},{en:'Hungry',zh:'饿的',ph:'/ˈhʌŋɡri/',ex:'I am hungry.'},{en:'Thirsty',zh:'渴的',ph:'/ˈθɜːrsti/',ex:'I am thirsty.'},{en:'Salt',zh:'盐',ph:'/sɔːlt/',ex:'Pass the salt, please.'}]},
    {id:7,name:'购物街区',progress:0,words:[{en:'Butcher',zh:'屠夫',ph:'/ˈbʊtʃər/',ex:'Go to the butcher.'},{en:'Baker',zh:'面包师',ph:'/ˈbeɪkər/',ex:'The baker makes bread.'},{en:'Grocer',zh:'杂货商',ph:'/ˈɡroʊsər/',ex:'The grocer sells food.'},{en:'Greengrocer',zh:'蔬菜水果商',ph:'/ˈɡriːnɡroʊsər/',ex:'Buy apples from the greengrocer.'},{en:'Shop',zh:'商店',ph:'/ʃɒp/',ex:'The shop is open.'},{en:'Buy',zh:'买',ph:'/baɪ/',ex:'Buy some meat.'},{en:'Sell',zh:'卖',ph:'/sel/',ex:'They sell vegetables.'},{en:'Price',zh:'价格',ph:'/praɪs/',ex:'The price is high.'},{en:'Cheap',zh:'便宜的',ph:'/tʃiːp/',ex:'It is very cheap.'},{en:'Expensive',zh:'昂贵的',ph:'/ɪkˈspensɪv/',ex:'The car is expensive.'},{en:'Money',zh:'钱',ph:'/ˈmʌni/',ex:'Do you have money?'},{en:'Pound',zh:'英镑',ph:'/paʊnd/',ex:'It costs ten pounds.'},{en:'Dollar',zh:'美元',ph:'/ˈdɒlər/',ex:'Give me five dollars.'},{en:'Cent',zh:'分',ph:'/sent/',ex:'Fifty cents.'},{en:'Want',zh:'想要',ph:'/wɒnt/',ex:'I want some apples.'},{en:'Need',zh:'需要',ph:'/niːd/',ex:'I need some help.'},{en:'Have',zh:'有',ph:'/hæv/',ex:'I have a car.'},{en:'Some',zh:'一些',ph:'/sʌm/',ex:'Give me some bread.'},{en:'Many',zh:'许多',ph:'/ˈmeni/',ex:'How many eggs?'},{en:'Much',zh:'许多',ph:'/mʌtʃ/',ex:'How much is it?'},{en:'Time',zh:'时间',ph:'/taɪm/',ex:'What is the time?'},{en:'Minute',zh:'分钟',ph:'/ˈmɪnɪt/',ex:'Wait a minute.'},{en:'Hour',zh:'小时',ph:'/ˈaʊər/',ex:'An hour later.'},{en:'Yesterday',zh:'昨天',ph:'/ˈjestərdeɪ/',ex:'Yesterday was Sunday.'},{en:'Tomorrow',zh:'明天',ph:'/təˈmɔːroʊ/',ex:'See you tomorrow.'}]},
    {id:8,name:'时间日常',progress:0,words:[{en:'Get up',zh:'起床',ph:'/ɡet ʌp/',ex:'I get up at seven.'},{en:'Shave',zh:'刮胡子',ph:'/ʃeɪv/',ex:'He shaves every morning.'},{en:'Teeth',zh:'牙齿',ph:'/tiːθ/',ex:'Brush your teeth.'},{en:'Home',zh:'家',ph:'/hoʊm/',ex:'Go home.'},{en:'Work',zh:'工作',ph:'/wɜːrk/',ex:'I work hard.'},{en:'Evening',zh:'傍晚',ph:'/ˈiːvnɪŋ/',ex:'Good evening.'},{en:'Night',zh:'夜晚',ph:'/naɪt/',ex:'Good night.'},{en:'Afternoon',zh:'下午',ph:'/ˌæftərˈnuːn/',ex:'Good afternoon.'},{en:'Noon',zh:'中午',ph:'/nuːn/',ex:'At noon.'},{en:'Every',zh:'每个',ph:'/ˈevri/',ex:'Every day.'},{en:'Day',zh:'天',ph:'/deɪ/',ex:'Have a nice day.'},{en:'Week',zh:'周',ph:'/wiːk/',ex:'A week has seven days.'},{en:'Month',zh:'月',ph:'/mʌnθ/',ex:'This month is June.'},{en:'Year',zh:'年',ph:'/jɪr/',ex:'Happy New Year.'},{en:'Spring',zh:'春天',ph:'/sprɪŋ/',ex:'Spring is warm.'},{en:'Summer',zh:'夏天',ph:'/ˈsʌmər/',ex:'Summer is hot.'},{en:'Autumn',zh:'秋天',ph:'/ˈɔːtəm/',ex:'Autumn is cool.'},{en:'Winter',zh:'冬天',ph:'/ˈwɪntər/',ex:'Winter is cold.'},{en:'Season',zh:'季节',ph:'/ˈsiːzn/',ex:'Four seasons.'},{en:'January',zh:'一月',ph:'/ˈdʒænjueri/',ex:'January is cold.'},{en:'February',zh:'二月',ph:'/ˈfebrueri/',ex:'February is short.'},{en:'March',zh:'三月',ph:'/mɑːrtʃ/',ex:'March is windy.'},{en:'April',zh:'四月',ph:'/ˈeɪprəl/',ex:'April is warm.'},{en:'June',zh:'六月',ph:'/dʒuːn/',ex:'June is hot.'},{en:'July',zh:'七月',ph:'/dʒuˈlaɪ/',ex:'July is sunny.'},{en:'August',zh:'八月',ph:'/ɔːˈɡʌst/',ex:'August is hot.'},{en:'September',zh:'九月',ph:'/sepˈtembər/',ex:'September is cool.'},{en:'October',zh:'十月',ph:'/ɒkˈtoʊbər/',ex:'October is nice.'}]},
    {id:9,name:'周末计划',progress:0,words:[{en:'Sunday',zh:'周日',ph:'/ˈsʌndeɪ/',ex:'Sunday is a holiday.'},{en:'Monday',zh:'周一',ph:'/ˈmʌndeɪ/',ex:'Monday morning.'},{en:'Tuesday',zh:'周二',ph:'/ˈtjuːzdeɪ/',ex:'Tuesday afternoon.'},{en:'Wednesday',zh:'周三',ph:'/ˈwenzdeɪ/',ex:'Wednesday evening.'},{en:'Thursday',zh:'周四',ph:'/ˈθɜːrzdeɪ/',ex:'Thursday night.'},{en:'Friday',zh:'周五',ph:'/ˈfraɪdeɪ/',ex:'Friday is fun.'},{en:'Saturday',zh:'周六',ph:'/ˈsætərdeɪ/',ex:'Saturday is weekend.'},{en:'Weekend',zh:'周末',ph:'/ˌwiːkˈend/',ex:'Have a nice weekend.'},{en:'Holiday',zh:'假日',ph:'/ˈhɒlədeɪ/',ex:'Summer holiday.'},{en:'Visit',zh:'拜访',ph:'/ˈvɪzɪt/',ex:'Visit my friend.'},{en:'Friend',zh:'朋友',ph:'/frend/',ex:'She is my friend.'},{en:'Stay',zh:'停留',ph:'/steɪ/',ex:'Stay at home.'},{en:'Play',zh:'玩',ph:'/pleɪ/',ex:'Play in the garden.'},{en:'Game',zh:'游戏',ph:'/ɡeɪm/',ex:'Play a game.'},{en:'Read',zh:'阅读',ph:'/riːd/',ex:'Read a book.'},{en:'Write',zh:'写',ph:'/raɪt/',ex:'Write a letter.'},{en:'Letter',zh:'信',ph:'/ˈletər/',ex:'Write a letter.'},{en:'Phone',zh:'电话',ph:'/foʊn/',ex:'Phone me.'},{en:'Call',zh:'打电话',ph:'/kɔːl/',ex:'Call the doctor.'},{en:'Together',zh:'一起',ph:'/təˈɡeðər/',ex:'We go together.'},{en:'With',zh:'和…一起',ph:'/wɪð/',ex:'Come with me.'},{en:'For',zh:'为了',ph:'/fɔːr/',ex:'A gift for you.'},{en:'But',zh:'但是',ph:'/bʌt/',ex:'But I am busy.'},{en:'Also',zh:'也',ph:'/ˈɔːlsoʊ/',ex:'I also like it.'},{en:'Very',zh:'非常',ph:'/ˈveri/',ex:'Very good.'},{en:'Too',zh:'太',ph:'/tuː/',ex:'Too expensive.'},{en:'Only',zh:'仅仅',ph:'/ˈoʊnli/',ex:'Only one.'},{en:'Really',zh:'真正地',ph:'/ˈriːəli/',ex:'Really nice.'}]},
    {id:10,name:'出行旅游',progress:0,words:[{en:'Left',zh:'左',ph:'/left/',ex:'Turn left.'},{en:'Right',zh:'右',ph:'/raɪt/',ex:'Turn right.'},{en:'Straight',zh:'直',ph:'/streɪt/',ex:'Go straight ahead.'},{en:'Road',zh:'路',ph:'/roʊd/',ex:'The road is long.'},{en:'Street',zh:'街道',ph:'/striːt/',ex:'Cross the street.'},{en:'Corner',zh:'拐角',ph:'/ˈkɔːrnər/',ex:'At the corner.'},{en:'Bridge',zh:'桥',ph:'/brɪdʒ/',ex:'Cross the bridge.'},{en:'River',zh:'河',ph:'/ˈrɪvər/',ex:'The river is wide.'},{en:'Stop',zh:'停',ph:'/stɒp/',ex:'Stop here.'},{en:'Bus',zh:'公共汽车',ph:'/bʌs/',ex:'Take the bus.'},{en:'Train',zh:'火车',ph:'/treɪn/',ex:'The train is fast.'},{en:'Boat',zh:'船',ph:'/boʊt/',ex:'A boat on the river.'},{en:'Taxi',zh:'出租车',ph:'/ˈtæksi/',ex:'Take a taxi.'},{en:'Drive',zh:'开车',ph:'/draɪv/',ex:'Drive carefully.'},{en:'Ride',zh:'骑',ph:'/raɪd/',ex:'Ride a bike.'},{en:'Always',zh:'总是',ph:'/ˈɔːlweɪz/',ex:'Always be kind.'},{en:'Often',zh:'经常',ph:'/ˈɔːfən/',ex:'I often read.'},{en:'Usually',zh:'通常',ph:'/ˈjuːʒuəli/',ex:'I usually walk.'},{en:'Never',zh:'从不',ph:'/ˈnevər/',ex:'I never smoke.'},{en:'Sometimes',zh:'有时',ph:'/ˈsʌmtaɪmz/',ex:'Sometimes I swim.'},{en:'Then',zh:'然后',ph:'/ðen/',ex:'Then go home.'},{en:'First',zh:'首先',ph:'/fɜːrst/',ex:'First, wash your hands.'},{en:'Next',zh:'接下来',ph:'/nekst/',ex:'Next, open the door.'},{en:'Last',zh:'最后',ph:'/læst/',ex:'Last week.'},{en:'Again',zh:'再次',ph:'/əˈɡen/',ex:'Say it again.'},{en:'Away',zh:'离开',ph:'/əˈweɪ/',ex:'Go away.'},{en:'About',zh:'大约',ph:'/əˈbaʊt/',ex:'About ten minutes.'}]},
    {id:11,name:'日常生活',progress:0,words:[{en:'Live',zh:'居住',ph:'/lɪv/',ex:'I live in London.'},{en:'Feel',zh:'感觉',ph:'/fiːl/',ex:'I feel tired.'},{en:'Tired',zh:'累的',ph:'/ˈtaɪərd/',ex:'I am very tired.'},{en:'Ill',zh:'生病的',ph:'/ɪl/',ex:'She is ill.'},{en:'Better',zh:'更好',ph:'/ˈbetər/',ex:'I feel better.'},{en:'Worse',zh:'更糟',ph:'/wɜːrs/',ex:'It is getting worse.'},{en:'Doctor',zh:'医生',ph:'/ˈdɒktər/',ex:'See a doctor.'},{en:'Medicine',zh:'药',ph:'/ˈmedɪsn/',ex:'Take the medicine.'},{en:'Rest',zh:'休息',ph:'/rest/',ex:'Have a rest.'},{en:'Headache',zh:'头痛',ph:'/ˈhedeɪk/',ex:'I have a headache.'},{en:'Toothache',zh:'牙痛',ph:'/ˈtuːθeɪk/',ex:'I have a toothache.'},{en:'Stomach',zh:'胃',ph:'/ˈstʌmək/',ex:'My stomach hurts.'},{en:'Temperature',zh:'体温',ph:'/ˈtemprətʃər/',ex:'Take your temperature.'},{en:'Aspirin',zh:'阿司匹林',ph:'/ˈæsprɪn/',ex:'Take an aspirin.'},{en:'Must',zh:'必须',ph:'/mʌst/',ex:'You must rest.'},{en:'Can',zh:'能',ph:'/kæn/',ex:'I can swim.'},{en:'May',zh:'可以',ph:'/meɪ/',ex:'May I come in?'},{en:'Could',zh:'可以',ph:'/kʊd/',ex:'Could you help me?'},{en:'Should',zh:'应该',ph:'/ʃʊd/',ex:'You should study.'},{en:'Think',zh:'想',ph:'/θɪŋk/',ex:'I think so.'},{en:'Know',zh:'知道',ph:'/noʊ/',ex:'I know the answer.'},{en:'Believe',zh:'相信',ph:'/bɪˈliːv/',ex:'I believe you.'},{en:'Remember',zh:'记住',ph:'/rɪˈmembər/',ex:'Remember the words.'},{en:'Forget',zh:'忘记',ph:'/fərˈɡet/',ex:'Do not forget.'},{en:'Hope',zh:'希望',ph:'/hoʊp/',ex:'I hope so.'},{en:'Find',zh:'找到',ph:'/faɪnd/',ex:'Find your book.'},{en:'Lose',zh:'丢失',ph:'/luːz/',ex:'Do not lose it.'}]},
    {id:12,name:'居家事物',progress:0,words:[{en:'Move',zh:'搬家',ph:'/muːv/',ex:'Move to a new house.'},{en:'Housework',zh:'家务',ph:'/ˈhaʊswɜːrk/',ex:'Do housework.'},{en:'Dust',zh:'灰尘',ph:'/dʌst/',ex:'Dust the table.'},{en:'Sweep',zh:'扫',ph:'/swiːp/',ex:'Sweep the floor.'},{en:'Air',zh:'通风',ph:'/eər/',ex:'Air the room.'},{en:'Make',zh:'整理',ph:'/meɪk/',ex:'Make the bed.'},{en:'Draw',zh:'拉',ph:'/drɔː/',ex:'Draw the curtain.'},{en:'Curtain',zh:'窗帘',ph:'/ˈkɜːrtn/',ex:'Close the curtain.'},{en:'Light',zh:'灯',ph:'/laɪt/',ex:'Turn on the light.'},{en:'Switch',zh:'开关',ph:'/swɪtʃ/',ex:'Switch it off.'},{en:'Put on',zh:'穿上',ph:'/pʊt ɒn/',ex:'Put on your coat.'},{en:'Take off',zh:'脱下',ph:'/teɪk ɒf/',ex:'Take off your shoes.'},{en:'Look after',zh:'照顾',ph:'/lʊk ˈæftər/',ex:'Look after the baby.'},{en:'Listen',zh:'听',ph:'/ˈlɪsn/',ex:'Listen to me.'},{en:'Wait',zh:'等待',ph:'/weɪt/',ex:'Wait for me.'},{en:'Hurry',zh:'赶快',ph:'/ˈhʌri/',ex:'Hurry up!'},{en:'Careful',zh:'小心的',ph:'/ˈkerfl/',ex:'Be careful!'},{en:'Quick',zh:'快的',ph:'/kwɪk/',ex:'Be quick.'},{en:'Slow',zh:'慢的',ph:'/sloʊ/',ex:'Slow down.'},{en:'Fast',zh:'快的',ph:'/fæst/',ex:'Run fast.'},{en:'Quiet',zh:'安静的',ph:'/ˈkwaɪət/',ex:'Be quiet.'},{en:'Loud',zh:'大声的',ph:'/laʊd/',ex:'Speak loud.'},{en:'Aloud',zh:'出声地',ph:'/əˈlaʊd/',ex:'Read aloud.'},{en:'Kitchen',zh:'厨房',ph:'/ˈkɪtʃɪn/',ex:'Clean the kitchen.'},{en:'Wash',zh:'洗',ph:'/wɒʃ/',ex:'Wash the dishes.'},{en:'Clean',zh:'打扫',ph:'/kliːn/',ex:'Clean the room.'}]},
    {id:13,name:'人物描述',progress:0,words:[{en:'Handsome',zh:'英俊的',ph:'/ˈhænsəm/',ex:'He is handsome.'},{en:'Pretty',zh:'漂亮的',ph:'/ˈprɪti/',ex:'She is pretty.'},{en:'Ugly',zh:'丑的',ph:'/ˈʌɡli/',ex:'Not ugly.'},{en:'Strong',zh:'强壮的',ph:'/strɒŋ/',ex:'He is strong.'},{en:'Weak',zh:'虚弱的',ph:'/wiːk/',ex:'She feels weak.'},{en:'Happy',zh:'快乐的',ph:'/ˈhæpi/',ex:'I am happy.'},{en:'Sad',zh:'伤心的',ph:'/sæd/',ex:'Do not be sad.'},{en:'Angry',zh:'生气的',ph:'/ˈæŋɡri/',ex:'She is angry.'},{en:'Afraid',zh:'害怕的',ph:'/əˈfreɪd/',ex:'I am afraid.'},{en:'Brave',zh:'勇敢的',ph:'/breɪv/',ex:'Be brave.'},{en:'Kind',zh:'善良的',ph:'/kaɪnd/',ex:'She is kind.'},{en:'Lazy',zh:'懒惰的',ph:'/ˈleɪzi/',ex:'Do not be lazy.'},{en:'Busy',zh:'忙的',ph:'/ˈbɪzi/',ex:'I am busy today.'},{en:'Free',zh:'空闲的',ph:'/friː/',ex:'Are you free?'},{en:'Ready',zh:'准备好的',ph:'/ˈredi/',ex:'Are you ready?'},{en:'Sure',zh:'确定的',ph:'/ʃʊr/',ex:'I am sure.'},{en:'Sorry',zh:'抱歉的',ph:'/ˈsɒri/',ex:'I am sorry.'},{en:'Glad',zh:'高兴的',ph:'/ɡlæd/',ex:'I am glad.'},{en:'Proud',zh:'自豪的',ph:'/praʊd/',ex:'I am proud of you.'},{en:'Shy',zh:'害羞的',ph:'/ʃaɪ/',ex:'She is shy.'},{en:'Clever',zh:'聪明的',ph:'/ˈklevər/',ex:'He is clever.'},{en:'Foolish',zh:'愚蠢的',ph:'/ˈfuːlɪʃ/',ex:'That is foolish.'},{en:'Rich',zh:'富有的',ph:'/rɪtʃ/',ex:'He is rich.'},{en:'Poor',zh:'贫穷的',ph:'/pʊr/',ex:'She is poor.'},{en:'Dear',zh:'亲爱的',ph:'/dɪr/',ex:'My dear friend.'},{en:'Great',zh:'伟大的',ph:'/ɡreɪt/',ex:'That is great!'},{en:'Wonderful',zh:'精彩的',ph:'/ˈwʌndərfl/',ex:'Wonderful idea!'}]},
    {id:14,name:'交流表达',progress:0,words:[{en:'Talk',zh:'谈话',ph:'/tɔːk/',ex:'Talk to me.'},{en:'Speak',zh:'说话',ph:'/spiːk/',ex:'Speak English.'},{en:'Say',zh:'说',ph:'/seɪ/',ex:'Say it again.'},{en:'Tell',zh:'告诉',ph:'/tel/',ex:'Tell me a story.'},{en:'Ask',zh:'问',ph:'/æsk/',ex:'Ask a question.'},{en:'Answer',zh:'回答',ph:'/ˈænsər/',ex:'Answer the question.'},{en:'Question',zh:'问题',ph:'/ˈkwestʃən/',ex:'Good question.'},{en:'Story',zh:'故事',ph:'/ˈstɔːri/',ex:'Tell a story.'},{en:'Secret',zh:'秘密',ph:'/ˈsiːkrət/',ex:'Keep the secret.'},{en:'News',zh:'新闻',ph:'/njuːz/',ex:'Good news!'},{en:'Message',zh:'消息',ph:'/ˈmesɪdʒ/',ex:'Leave a message.'},{en:'Meaning',zh:'意思',ph:'/ˈmiːnɪŋ/',ex:'What is the meaning?'},{en:'Nothing',zh:'没什么',ph:'/ˈnʌθɪŋ/',ex:'Nothing is wrong.'},{en:'Something',zh:'某事',ph:'/ˈsʌmθɪŋ/',ex:'Something is wrong.'},{en:'Everything',zh:'一切',ph:'/ˈevriθɪŋ/',ex:'Everything is OK.'},{en:'Wrong',zh:'错的',ph:'/rɒŋ/',ex:'Something is wrong.'},{en:'Right',zh:'对的',ph:'/raɪt/',ex:'You are right.'},{en:'True',zh:'真的',ph:'/truː/',ex:'It is true.'},{en:'Correct',zh:'正确的',ph:'/kəˈrekt/',ex:'Correct answer.'},{en:'Mistake',zh:'错误',ph:'/mɪˈsteɪk/',ex:'Make a mistake.'},{en:'Problem',zh:'问题',ph:'/ˈprɒbləm/',ex:'No problem.'},{en:'Idea',zh:'主意',ph:'/aɪˈdɪə/',ex:'Good idea!'},{en:'Help',zh:'帮助',ph:'/help/',ex:'I need help.'},{en:'Important',zh:'重要的',ph:'/ɪmˈpɔːrtnt/',ex:'It is important.'},{en:'Necessary',zh:'必要的',ph:'/ˈnesəseri/',ex:'It is necessary.'},{en:'Different',zh:'不同的',ph:'/ˈdɪfrənt/',ex:'Different ideas.'},{en:'Same',zh:'相同的',ph:'/seɪm/',ex:'The same thing.'}]},
    {id:15,name:'出行交通',progress:0,words:[{en:'Airport',zh:'机场',ph:'/ˈeərpɔːrt/',ex:'Go to the airport.'},{en:'Station',zh:'车站',ph:'/ˈsteɪʃn/',ex:'The train station.'},{en:'Platform',zh:'站台',ph:'/ˈplætfɔːrm/',ex:'Platform 5.'},{en:'Catch',zh:'赶上',ph:'/kætʃ/',ex:'Catch the train.'},{en:'Miss',zh:'错过',ph:'/mɪs/',ex:'Do not miss it.'},{en:'Leave',zh:'离开',ph:'/liːv/',ex:'The train leaves.'},{en:'Arrive',zh:'到达',ph:'/əˈraɪv/',ex:'Arrive on time.'},{en:'Travel',zh:'旅行',ph:'/ˈtrævl/',ex:'Travel by train.'},{en:'Journey',zh:'旅程',ph:'/ˈdʒɜːrni/',ex:'A long journey.'},{en:'Trip',zh:'旅行',ph:'/trɪp/',ex:'A nice trip.'},{en:'Abroad',zh:'国外',ph:'/əˈbrɔːd/',ex:'Go abroad.'},{en:'Country',zh:'国家',ph:'/ˈkʌntri/',ex:'A beautiful country.'},{en:'Town',zh:'城镇',ph:'/taʊn/',ex:'Go to town.'},{en:'City',zh:'城市',ph:'/ˈsɪti/',ex:'The city is big.'},{en:'Village',zh:'村庄',ph:'/ˈvɪlɪdʒ/',ex:'A small village.'},{en:'Farm',zh:'农场',ph:'/fɑːrm/',ex:'The farm is big.'},{en:'Field',zh:'田地',ph:'/fiːld/',ex:'The field is green.'},{en:'Mountain',zh:'山',ph:'/ˈmaʊntn/',ex:'High mountains.'},{en:'Sea',zh:'海',ph:'/siː/',ex:'The sea is blue.'},{en:'Lake',zh:'湖',ph:'/leɪk/',ex:'A beautiful lake.'},{en:'Forest',zh:'森林',ph:'/ˈfɒrɪst/',ex:'Walk in the forest.'},{en:'Map',zh:'地图',ph:'/mæp/',ex:'Read the map.'},{en:'Way',zh:'路',ph:'/weɪ/',ex:'Find the way.'},{en:'Mile',zh:'英里',ph:'/maɪl/',ex:'Ten miles away.'},{en:'Kilometre',zh:'公里',ph:'/ˈkɪləmiːtər/',ex:'Five kilometres.'},{en:'Far',zh:'远的',ph:'/fɑːr/',ex:'Is it far?'},{en:'Near',zh:'近的',ph:'/nɪr/',ex:'It is near.'}]},
    {id:16,name:'人际关系',progress:0,words:[{en:'Family',zh:'家庭',ph:'/ˈfæməli/',ex:'My family is big.'},{en:'Father',zh:'父亲',ph:'/ˈfɑːðər/',ex:'My father works.'},{en:'Mother',zh:'母亲',ph:'/ˈmʌðər/',ex:'My mother cooks.'},{en:'Brother',zh:'兄弟',ph:'/ˈbrʌðər/',ex:'My brother is tall.'},{en:'Sister',zh:'姐妹',ph:'/ˈsɪstər/',ex:'My sister is young.'},{en:'Husband',zh:'丈夫',ph:'/ˈhʌzbənd/',ex:'Her husband is kind.'},{en:'Wife',zh:'妻子',ph:'/waɪf/',ex:'His wife is pretty.'},{en:'Baby',zh:'婴儿',ph:'/ˈbeɪbi/',ex:'The baby is cute.'},{en:'Child',zh:'孩子',ph:'/tʃaɪld/',ex:'The child is happy.'},{en:'Boy',zh:'男孩',ph:'/bɔɪ/',ex:'The boy runs.'},{en:'Girl',zh:'女孩',ph:'/ɡɜːrl/',ex:'The girl sings.'},{en:'Man',zh:'男人',ph:'/mæn/',ex:'The man is strong.'},{en:'Woman',zh:'女人',ph:'/ˈwʊmən/',ex:'The woman is smart.'},{en:'People',zh:'人们',ph:'/ˈpiːpl/',ex:'People are nice.'},{en:'Name',zh:'名字',ph:'/neɪm/',ex:'What is your name?'},{en:'Friend',zh:'朋友',ph:'/frend/',ex:'My best friend.'},{en:'Neighbour',zh:'邻居',ph:'/ˈneɪbər/',ex:'Our neighbour is kind.'},{en:'Guest',zh:'客人',ph:'/ɡest/',ex:'We have a guest.'},{en:'Welcome',zh:'欢迎',ph:'/ˈwelkəm/',ex:'Welcome home!'},{en:'Invite',zh:'邀请',ph:'/ɪnˈvaɪt/',ex:'Invite him to dinner.'},{en:'Party',zh:'聚会',ph:'/ˈpɑːrti/',ex:'Have a party.'},{en:'Gift',zh:'礼物',ph:'/ɡɪft/',ex:'A gift for you.'},{en:'Surprise',zh:'惊喜',ph:'/sərˈpraɪz/',ex:'What a surprise!'},{en:'Love',zh:'爱',ph:'/lʌv/',ex:'I love my family.'},{en:'Miss',zh:'想念',ph:'/mɪs/',ex:'I miss you.'},{en:'Enjoy',zh:'享受',ph:'/ɪnˈdʒɔɪ/',ex:'Enjoy the party.'},{en:'Share',zh:'分享',ph:'/ʃeər/',ex:'Share with others.'}]},
    {id:17,name:'运动爱好',progress:0,words:[{en:'Sport',zh:'运动',ph:'/spɔːrt/',ex:'I like sports.'},{en:'Swim',zh:'游泳',ph:'/swɪm/',ex:'Go swimming.'},{en:'Run',zh:'跑步',ph:'/rʌn/',ex:'Go running.'},{en:'Walk',zh:'散步',ph:'/wɔːk/',ex:'Go for a walk.'},{en:'Football',zh:'足球',ph:'/ˈfʊtbɔːl/',ex:'Play football.'},{en:'Basketball',zh:'篮球',ph:'/ˈbæskɪtbɔːl/',ex:'Play basketball.'},{en:'Win',zh:'赢',ph:'/wɪn/',ex:'We win the match.'},{en:'Lose',zh:'输',ph:'/luːz/',ex:'Do not lose hope.'},{en:'Team',zh:'队伍',ph:'/tiːm/',ex:'Our team wins.'},{en:'Ball',zh:'球',ph:'/bɔːl/',ex:'Throw the ball.'},{en:'Music',zh:'音乐',ph:'/ˈmjuːzɪk/',ex:'Listen to music.'},{en:'Song',zh:'歌曲',ph:'/sɒŋ/',ex:'Sing a song.'},{en:'Sing',zh:'唱',ph:'/sɪŋ/',ex:'She sings well.'},{en:'Dance',zh:'跳舞',ph:'/dæns/',ex:'Let us dance.'},{en:'Paint',zh:'画画',ph:'/peɪnt/',ex:'Paint a picture.'},{en:'Draw',zh:'画',ph:'/drɔː/',ex:'Draw a flower.'},{en:'Film',zh:'电影',ph:'/fɪlm/',ex:'Watch a film.'},{en:'Theatre',zh:'剧院',ph:'/ˈθɪətər/',ex:'Go to the theatre.'},{en:'Cinema',zh:'电影院',ph:'/ˈsɪnəmə/',ex:'Go to the cinema.'},{en:'Concert',zh:'音乐会',ph:'/ˈkɑːnsərt/',ex:'A wonderful concert.'},{en:'Hobby',zh:'爱好',ph:'/ˈhɒbi/',ex:'My hobby is reading.'},{en:'Collect',zh:'收集',ph:'/kəˈlekt/',ex:'Collect stamps.'},{en:'Stamp',zh:'邮票',ph:'/stæmp/',ex:'A beautiful stamp.'},{en:'Camera',zh:'相机',ph:'/ˈkæmərə/',ex:'My camera is new.'},{en:'Photo',zh:'照片',ph:'/ˈfoʊtoʊ/',ex:'Take a photo.'},{en:'Garden',zh:'花园',ph:'/ˈɡɑːrdn/',ex:'Beautiful garden.'},{en:'Flower',zh:'花',ph:'/ˈflaʊər/',ex:'The flower is red.'}]},
    {id:18,name:'梦想未来',progress:0,words:[{en:'Dream',zh:'梦想',ph:'/driːm/',ex:'Follow your dream.'},{en:'Future',zh:'未来',ph:'/ˈfjuːtʃər/',ex:'The future is bright.'},{en:'Plan',zh:'计划',ph:'/plæn/',ex:'Make a plan.'},{en:'Goal',zh:'目标',ph:'/ɡoʊl/',ex:'Set a goal.'},{en:'Try',zh:'尝试',ph:'/traɪ/',ex:'Try your best.'},{en:'Learn',zh:'学习',ph:'/lɜːrn/',ex:'Learn English.'},{en:'Study',zh:'学习',ph:'/ˈstʌdi/',ex:'Study hard.'},{en:'Practice',zh:'练习',ph:'/ˈpræktɪs/',ex:'Practice every day.'},{en:'Improve',zh:'提高',ph:'/ɪmˈpruːv/',ex:'Improve your English.'},{en:'Achieve',zh:'实现',ph:'/əˈtʃiːv/',ex:'Achieve your dream.'},{en:'Success',zh:'成功',ph:'/səkˈses/',ex:'Success is coming.'},{en:'Hard',zh:'努力的',ph:'/hɑːrd/',ex:'Work hard.'},{en:'Easy',zh:'容易的',ph:'/ˈiːzi/',ex:'It is easy.'},{en:'Difficult',zh:'困难的',ph:'/ˈdɪfɪkəlt/',ex:'Not difficult.'},{en:'Simple',zh:'简单的',ph:'/ˈsɪmpl/',ex:'Very simple.'},{en:'Special',zh:'特别的',ph:'/ˈspeʃl/',ex:'A special day.'},{en:'Enjoy',zh:'享受',ph:'/ɪnˈdʒɔɪ/',ex:'Enjoy your life.'},{en:'Life',zh:'生活',ph:'/laɪf/',ex:'Life is beautiful.'},{en:'World',zh:'世界',ph:'/wɜːrld/',ex:'Explore the world.'},{en:'Change',zh:'改变',ph:'/tʃeɪndʒ/',ex:'Change your life.'},{en:'Start',zh:'开始',ph:'/stɑːrt/',ex:'Start now.'},{en:'Finish',zh:'完成',ph:'/ˈfɪnɪʃ/',ex:'Finish your work.'},{en:'Continue',zh:'继续',ph:'/kənˈtɪnjuː/',ex:'Continue learning.'},{en:'Confident',zh:'自信的',ph:'/ˈkɒnfɪdənt/',ex:'Be confident.'},{en:'Perfect',zh:'完美的',ph:'/ˈpɜːrfɪkt/',ex:'Practice makes perfect.'},{en:'Excellent',zh:'优秀的',ph:'/ˈeksələnt/',ex:'Excellent work!'},{en:'Language',zh:'语言',ph:'/ˈlæŋɡwɪdʒ/',ex:'Learn a language.'}]}
],
  articles:[
    {id:1,title:'Su Shi: A Life of Optimism',titleZh:'苏轼：豁达一生',category:'传统文化',color:'#ec4899',level:'450L',time:'8分钟',collected:false},
    {id:2,title:'Climate Change: A Global Challenge',titleZh:'气候变化：全球挑战',category:'时事热点',color:'#3b82f6',level:'350L',time:'6分钟',collected:false},
    {id:3,title:'The Power of Reading',titleZh:'阅读的力量',category:'晨读美文',color:'#f59e0b',level:'280L',time:'5分钟',collected:false},
    {id:4,title:'Technology and Life',titleZh:'科技与生活',category:'科技创新',color:'#f97316',level:'400L',time:'7分钟',collected:false},
    {id:5,title:'Nature Conservation',titleZh:'自然保护',category:'自然奥秘',color:'#10b981',level:'380L',time:'6分钟',collected:false},
    {id:6,title:'Fairy Tales Around the World',titleZh:'世界童话',category:'童话故事',color:'#8b5cf6',level:'320L',time:'5分钟',collected:false}
  ],
  articleContent:{
    1:{paragraphs:[
      {en:'Su Shi (1037–1101), also known as Su Dongpo, was one of the greatest poets in Chinese history.',zh:'苏轼（1037–1101），又名苏东坡，是中国历史上最伟大的诗人之一。'},
      {en:'He lived during the Song Dynasty and wrote many beautiful poems about nature, life, and friendship.',zh:'他生活在宋朝，写了许多关于自然、生活和友谊的优美诗歌。'},
      {en:'Su Shi faced many difficult times in his life. He lost his job and had to move to faraway places.',zh:'苏轼一生经历了许多困难时期。他失去了官职，被迫迁往偏远之地。'},
      {en:'But he never gave up. He found joy in simple things like cooking, painting, and walking in the rain.',zh:'但他从未放弃。他在烹饪、绘画和雨中漫步等简单事物中找到了快乐。'},
      {en:'He is famous for his optimistic spirit. He once wrote, "The moon has its ups and downs, just like life."',zh:'他以乐观精神著称。他曾写道："人有悲欢离合，月有阴晴圆缺。"'},
      {en:'Today, people still love his poems. His story teaches us to stay strong and smile, even when life is hard.',zh:'今天，人们依然热爱他的诗歌。他的故事教会我们，即使生活艰难，也要保持坚强和微笑。'},
    ]},
    2:{paragraphs:[
      {en:'Climate change is one of the biggest problems facing our world today.',zh:'气候变化是当今世界面临的最大问题之一。'},
      {en:'The Earth is getting warmer because of greenhouse gases like carbon dioxide.',zh:'由于二氧化碳等温室气体，地球正在变暖。'},
      {en:'This causes ice to melt, sea levels to rise, and more extreme weather like floods and droughts.',zh:'这导致冰川融化、海平面上升，以及洪水、干旱等更极端的天气。'},
      {en:'But there are things we can do. We can use less energy, walk or bike instead of driving, and recycle more.',zh:'但我们能做的事情也很多。我们可以减少能源消耗，步行或骑自行车代替开车，以及更多地回收利用。'},
      {en:'Every small action helps. If everyone does their part, we can make a big difference.',zh:'每一个小行动都有帮助。如果每个人都尽自己的一份力，我们就能带来巨大的改变。'},
      {en:'Let us work together to protect our planet for future generations.',zh:'让我们一起努力，为子孙后代保护我们的地球。'},
    ]},
    3:{paragraphs:[
      {en:'Reading is a wonderful habit that can change your life.',zh:'阅读是一个奇妙的习惯，它可以改变你的人生。'},
      {en:'When you read, you learn new words and ideas. You travel to different worlds without leaving your room.',zh:'当你阅读时，你会学到新单词和新思想。你足不出户就能旅行到不同的世界。'},
      {en:'Reading also makes you smarter. It helps you think better and understand other people\'s feelings.',zh:'阅读也能让你更聪明。它帮助你更好地思考，并理解他人的感受。'},
      {en:'You can read anywhere — on the bus, before bed, or during a break. Just ten pages a day is a good start.',zh:'你可以在任何地方阅读——在公交车上、睡前或休息时。每天只读十页就是一个好的开始。'},
      {en:'Try to read different kinds of books: stories, news, or non-fiction. Every book teaches you something new.',zh:'尝试阅读不同类型的书籍：故事、新闻或非虚构作品。每一本书都会教给你新的东西。'},
      {en:'Remember: today a reader, tomorrow a leader. Start your reading journey today!',zh:'记住：今天的阅读者，明天的领导者。从今天开始你的阅读之旅吧！'},
    ]},
    4:{paragraphs:[
      {en:'Technology has changed the way we live, work, and communicate.',zh:'科技改变了我们生活、工作和交流的方式。'},
      {en:'Smartphones and the Internet connect us with people all over the world in just seconds.',zh:'智能手机和互联网让我们能在几秒钟内与世界各地的人们联系。'},
      {en:'We can learn online, shop without leaving home, and even see our friends on video calls.',zh:'我们可以在线学习、足不出户购物，甚至通过视频通话见到朋友。'},
      {en:'But technology also has challenges. Spending too much time on screens is bad for our eyes and health.',zh:'但科技也带来了挑战。在屏幕前花费太多时间对眼睛和健康有害。'},
      {en:'It is important to find a balance. Use technology to help you, but do not let it control your life.',zh:'找到平衡很重要。让科技帮助你，但不要让它控制你的生活。'},
      {en:'When we use technology wisely, it makes our lives better and easier.',zh:'当我们明智地使用科技时，它会让我们的生活更美好、更便捷。'},
    ]},
    5:{paragraphs:[
      {en:'Nature is beautiful and full of wonders. Forests, rivers, mountains, and oceans are home to millions of animals and plants.',zh:'大自然是美丽而充满奇迹的。森林、河流、山脉和海洋是数百万动植物的家园。'},
      {en:'But many of these places are in danger. People cut down trees, pollute rivers, and destroy habitats.',zh:'但许多这样的地方正面临危险。人们砍伐树木、污染河流、破坏栖息地。'},
      {en:'When we lose one animal or plant, it affects everything else. Nature is like a big family — everyone needs each other.',zh:'当我们失去一种动物或植物，就会影响到其他一切。大自然就像一个大家庭——彼此需要。'},
      {en:'The good news is that people are working to protect nature. They plant trees, clean rivers, and create wildlife reserves.',zh:'好消息是人们正在努力保护大自然。他们植树、清理河流、建立野生动物保护区。'},
      {en:'You can help too! Do not litter, save water, and respect the animals and plants around you.',zh:'你也可以帮忙！不要乱扔垃圾，节约用水，尊重你周围的动植物。'},
      {en:'Together, we can keep our Earth green and beautiful for years to come.',zh:'我们一起努力，让我们的地球在未来依然绿色而美丽。'},
    ]},
    6:{paragraphs:[
      {en:'Once upon a time, in a small village, there lived a kind girl named Little Red Riding Hood.',zh:'从前，在一个小村庄里，住着一个善良的女孩叫小红帽。'},
      {en:'She loved to visit her grandmother, who lived on the other side of the forest.',zh:'她喜欢去看望住在森林另一边的奶奶。'},
      {en:'One day, while walking through the forest, she met a big gray wolf. The wolf had a clever but scary plan.',zh:'一天，当她穿过森林时，遇到了一只大灰狼。狼有一个狡猾又可怕的计划。'},
      {en:'Stories like this are found in every culture. They teach us lessons about courage, kindness, and wisdom.',zh:'这样的故事在每个文化中都能找到。它们教会我们关于勇气、善良和智慧的道理。'},
      {en:'Fairy tales help children learn about the world in a fun and magical way.',zh:'童话故事帮助孩子们用有趣而神奇的方式了解世界。'},
      {en:'No matter how old we are, these stories always remind us that good will win over evil in the end.',zh:'无论我们多大，这些故事总是提醒我们：正义最终会战胜邪恶。'},
    ]}
	  },
	  articleWords:{
	    1:[
	      {en:'poet',zh:'诗人',ph:'/ˈpoʊət/'},{en:'dynasty',zh:'王朝，朝代',ph:'/ˈdaɪnəsti/'},{en:'nature',zh:'自然',ph:'/ˈneɪtʃər/'},{en:'faraway',zh:'遥远的',ph:'/ˌfɑːrəˈweɪ/'},{en:'optimistic',zh:'乐观的',ph:'/ˌɑːptɪˈmɪstɪk/'},{en:'spirit',zh:'精神',ph:'/ˈspɪrɪt/'},{en:'famous',zh:'著名的',ph:'/ˈfeɪməs/'},{en:'stay strong',zh:'保持坚强',ph:'/steɪ strɒŋ/'}
	    ],
	    2:[
	      {en:'climate',zh:'气候',ph:'/ˈklaɪmət/'},{en:'greenhouse',zh:'温室',ph:'/ˈɡriːnhaʊs/'},{en:'carbon dioxide',zh:'二氧化碳',ph:'/ˈkɑːrbən daɪˈɑːksaɪd/'},{en:'extreme',zh:'极端的',ph:'/ɪkˈstriːm/'},{en:'energy',zh:'能源',ph:'/ˈenərdʒi/'},{en:'recycle',zh:'回收利用',ph:'/ˌriːˈsaɪkl/'},{en:'protect',zh:'保护',ph:'/prəˈtekt/'},{en:'planet',zh:'行星，地球',ph:'/ˈplænɪt/'},{en:'generation',zh:'一代人',ph:'/ˌdʒenəˈreɪʃn/'}
	    ],
	    3:[
	      {en:'habit',zh:'习惯',ph:'/ˈhæbɪt/'},{en:'smarter',zh:'更聪明的',ph:'/ˈsmɑːrtər/'},{en:'understand',zh:'理解',ph:'/ˌʌndərˈstænd/'},{en:'fiction',zh:'小说',ph:'/ˈfɪkʃn/'},{en:'non-fiction',zh:'非虚构作品',ph:'/nɒn ˈfɪkʃn/'},{en:'reader',zh:'读者',ph:'/ˈriːdər/'},{en:'leader',zh:'领导者',ph:'/ˈliːdər/'},{en:'journey',zh:'旅程',ph:'/ˈdʒɜːrni/'}
	    ],
	    4:[
	      {en:'technology',zh:'技术',ph:'/tekˈnɑːlədʒi/'},{en:'communicate',zh:'交流',ph:'/kəˈmjuːnɪkeɪt/'},{en:'smartphone',zh:'智能手机',ph:'/ˈsmɑːrtfoʊn/'},{en:'Internet',zh:'互联网',ph:'/ˈɪntərnet/'},{en:'balance',zh:'平衡',ph:'/ˈbæləns/'},{en:'control',zh:'控制',ph:'/kənˈtroʊl/'},{en:'wisely',zh:'明智地',ph:'/ˈwaɪzli/'},{en:'convenient',zh:'方便的',ph:'/kənˈviːniənt/'}
	    ],
	    5:[
	      {en:'nature',zh:'大自然',ph:'/ˈneɪtʃər/'},{en:'wonder',zh:'奇迹',ph:'/ˈwʌndər/'},{en:'pollute',zh:'污染',ph:'/pəˈluːt/'},{en:'destroy',zh:'破坏',ph:'/dɪˈstrɔɪ/'},{en:'habitat',zh:'栖息地',ph:'/ˈhæbɪtæt/'},{en:'affect',zh:'影响',ph:'/əˈfekt/'},{en:'reserve',zh:'保护区',ph:'/rɪˈzɜːrv/'},{en:'respect',zh:'尊重',ph:'/rɪˈspekt/'}
	    ],
	    6:[
	      {en:'fairy tale',zh:'童话',ph:'/ˈferi teɪl/'},{en:'grandmother',zh:'祖母',ph:'/ˈɡrænmʌðər/'},{en:'forest',zh:'森林',ph:'/ˈfɔːrɪst/'},{en:'clever',zh:'聪明的',ph:'/ˈklevər/'},{en:'courage',zh:'勇气',ph:'/ˈkɜːrɪdʒ/'},{en:'kindness',zh:'善良',ph:'/ˈkaɪndnəs/'},{en:'wisdom',zh:'智慧',ph:'/ˈwɪzdəm/'},{en:'magical',zh:'神奇的',ph:'/ˈmædʒɪkl/'},{en:'win over',zh:'战胜',ph:'/wɪn ˈoʊvər/'}
	    ]
	  },
	  reciteTexts:{
    1:{title:'Excuse Me!',sentences:[{en:'Excuse me.',zh:'对不起，打扰一下。'},{en:'Yes, sir?',zh:'什么事，先生？'},{en:'Is this your handbag?',zh:'这是你的手提包吗？'},{en:'Pardon?',zh:'请再说一遍？'},{en:'Oh yes, thank you very much.',zh:'哦是的，非常感谢。'},{en:'Please sit down.',zh:'请坐。'},{en:'Nice to meet you.',zh:'很高兴认识你。'},{en:'Nice to meet you too.',zh:'我也很高兴认识你。'}]},
    2:{title:'Colours and Things',sentences:[{en:'What colour is your new dress?',zh:'你的新裙子是什么颜色？'},{en:'It is green.',zh:'它是绿色的。'},{en:'My coat is blue and my shoes are black.',zh:'我的外套是蓝色的，鞋子是黑色的。'},{en:'The sky is blue and the sun is yellow.',zh:'天空是蓝色的，太阳是黄色的。'},{en:'Her eyes are brown and her hair is black.',zh:'她的眼睛是棕色的，头发是黑色的。'},{en:'The old house is clean and white.',zh:'老房子干净又洁白。'},{en:'The young girl has a big red box.',zh:'小女孩有一个大红盒子。'}]},
    3:{title:'Daily Life at Home',sentences:[{en:'Open the door, please.',zh:'请开门。'},{en:'Close the window and sit down.',zh:'关上窗户坐下来。'},{en:'This is my bedroom.',zh:'这是我的卧室。'},{en:'The kitchen is clean.',zh:'厨房很干净。'},{en:'The garden is lovely.',zh:'花园很可爱。'},{en:'A cup of tea, please.',zh:'请给我一杯茶。'},{en:'The glass is full of water.',zh:'玻璃杯装满了水。'}]},
    4:{title:'Household Items',sentences:[{en:'The refrigerator is in the kitchen.',zh:'冰箱在厨房里。'},{en:'Put the plate in the cupboard.',zh:'把盘子放在碗柜里。'},{en:'The picture is on the wall.',zh:'画挂在墙上。'},{en:'The lamp is on the desk.',zh:'台灯在书桌上。'},{en:'The knife is sharp, be careful.',zh:'刀很锋利，小心点。'},{en:'A bottle of milk is on the table.',zh:'一瓶牛奶在桌子上。'},{en:'The carpet is red and soft.',zh:'地毯是红色且柔软的。'}]},
    5:{title:'Weather and Actions',sentences:[{en:'The weather is nice today.',zh:'今天天气很好。'},{en:'The sun is shining in the sky.',zh:'阳光在天空中照耀。'},{en:'It is not raining now.',zh:'现在没下雨。'},{en:'Walk across the road carefully.',zh:'小心穿过马路。'},{en:'The bird flies high in the sky.',zh:'鸟在天空高飞。'},{en:'Sleep well at night.',zh:'晚上睡个好觉。'},{en:'Cook dinner with your mother.',zh:'和你妈妈一起做晚饭。'}]},
    6:{title:'Food and Meals',sentences:[{en:'Breakfast is ready.',zh:'早餐准备好了。'},{en:'I eat bread and eggs.',zh:'我吃面包和鸡蛋。'},{en:'A cup of coffee, please.',zh:'请给我一杯咖啡。'},{en:'The chicken is very good.',zh:'鸡肉很好吃。'},{en:'The fish is fresh.',zh:'鱼很新鲜。'},{en:'We eat rice for lunch.',zh:'我们午饭吃米饭。'},{en:'An apple a day is healthy.',zh:'一天一个苹果很健康。'}]},
    7:{title:'Shopping',sentences:[{en:'Go to the grocer to buy food.',zh:'去杂货店买食物。'},{en:'Buy some bread and butter.',zh:'买一些面包和黄油。'},{en:'How much is it?',zh:'这个多少钱？'},{en:'Two pounds, please.',zh:'请给我两英镑。'},{en:'That is very cheap.',zh:'那很便宜。'},{en:'I need some apples for dinner.',zh:'我需要一些苹果做晚饭。'},{en:'Do you have enough money?',zh:'你有足够的钱吗？'}]},
    8:{title:'Time and Seasons',sentences:[{en:'I get up at seven every morning.',zh:'我每天早上七点起床。'},{en:'I brush my teeth and go to work.',zh:'我刷牙然后去上班。'},{en:'Good evening. How are you today?',zh:'晚上好。你今天怎么样？'},{en:'Spring is warm and summer is hot.',zh:'春天温暖，夏天炎热。'},{en:'Autumn is cool and winter is cold.',zh:'秋天凉爽，冬天寒冷。'},{en:'A year has twelve months.',zh:'一年有十二个月。'},{en:'Every day is a nice day.',zh:'每一天都是美好的一天。'}]},
    9:{title:'Weekend Plans',sentences:[{en:'Sunday is a holiday.',zh:'星期天是假日。'},{en:'I visit my friend on Saturday.',zh:'我星期六拜访朋友。'},{en:'We stay at home and play games.',zh:'我们呆在家里玩游戏。'},{en:'We read a book together.',zh:'我们一起看书。'},{en:'I call my mother on the phone.',zh:'我打电话给我妈妈。'},{en:'Come with me to the party.',zh:'跟我一起去聚会吧。'},{en:'Have a nice weekend!',zh:'周末愉快！'}]},
    10:{title:'Travel and Directions',sentences:[{en:'Go straight ahead.',zh:'一直往前走。'},{en:'Turn left at the corner.',zh:'在拐角处左转。'},{en:'Cross the bridge over the river.',zh:'穿过河上的桥。'},{en:'Take the bus or the train.',zh:'坐公共汽车或火车。'},{en:'Take a taxi to the airport.',zh:'打车去机场。'},{en:'I always travel by train.',zh:'我总是坐火车旅行。'},{en:'Sometimes I walk to the town.',zh:'有时我步行去镇上。'}]},
    11:{title:'Feeling Well',sentences:[{en:'I live in a small town.',zh:'我住在一个小镇上。'},{en:'I feel very tired today.',zh:'我今天感觉很累。'},{en:'I have a headache.',zh:'我头疼。'},{en:'You must rest and take medicine.',zh:'你必须休息吃药。'},{en:'I think I am feeling better now.',zh:'我觉得我现在好多了。'},{en:'Do not forget to see the doctor.',zh:'别忘了看医生。'},{en:'I hope you feel well soon.',zh:'希望你早日康复。'}]},
    12:{title:'Housework',sentences:[{en:'Make the bed every morning.',zh:'每天早上整理床铺。'},{en:'Sweep the floor and dust the table.',zh:'扫地擦桌子。'},{en:'Put on your coat before you go out.',zh:'出门前穿上外套。'},{en:'Take off your shoes at the door.',zh:'在门口脱鞋。'},{en:'Look after the baby carefully.',zh:'小心照顾宝宝。'},{en:'Hurry up! Be quick!',zh:'快点！赶快！'},{en:'Be quiet and read aloud.',zh:'安静地大声朗读。'}]},
    13:{title:'Describing People',sentences:[{en:'He is handsome and strong.',zh:'他英俊又强壮。'},{en:'She is pretty and very kind.',zh:'她漂亮又善良。'},{en:'I am happy today.',zh:'我今天很开心。'},{en:'Do not be sad or angry.',zh:'不要伤心或生气。'},{en:'Be brave and clever.',zh:'勇敢又聪明。'},{en:'The rich man is proud of his car.',zh:'那个富人为他的车骄傲。'},{en:'The poor girl is shy but wonderful.',zh:'那个可怜的女孩害羞但很棒。'}]},
    14:{title:'Communication',sentences:[{en:'Speak English every day.',zh:'每天说英语。'},{en:'Say it again, please.',zh:'请再说一遍。'},{en:'Tell me an interesting story.',zh:'给我讲个有趣的故事。'},{en:'Ask me a question.',zh:'问我一个问题。'},{en:'That is the correct answer.',zh:'那是正确答案。'},{en:'Good idea! No problem!',zh:'好主意！没问题！'},{en:'Everything is OK now.',zh:'现在一切都好了。'}]},
    15:{title:'Transportation',sentences:[{en:'Go to the train station.',zh:'去火车站。'},{en:'Catch the train at platform five.',zh:'在五号站台上火车。'},{en:'Do not miss the train.',zh:'别错过了火车。'},{en:'The train leaves at noon.',zh:'火车中午出发。'},{en:'Arrive at the city on time.',zh:'准时到达城市。'},{en:'The journey is long but beautiful.',zh:'旅程漫长但美好。'},{en:'The village is near the mountain.',zh:'村庄在山的附近。'}]},
    16:{title:'My Family',sentences:[{en:'This is my family.',zh:'这是我的家人。'},{en:'My father works in the city.',zh:'我爸爸在城市工作。'},{en:'My mother cooks in the kitchen.',zh:'我妈妈在厨房做饭。'},{en:'My brother is tall and strong.',zh:'我哥哥高大又强壮。'},{en:'Welcome to my home!',zh:'欢迎来我家！'},{en:'I love my family very much.',zh:'我非常爱我的家人。'},{en:'Share your toys with others.',zh:'和别人分享你的玩具。'}]},
    17:{title:'Sports and Hobbies',sentences:[{en:'I like sports very much.',zh:'我非常喜欢运动。'},{en:'I go swimming on Saturday.',zh:'我星期六去游泳。'},{en:'We play football in the garden.',zh:'我们在花园里踢足球。'},{en:'Our team always wins.',zh:'我们队总是赢。'},{en:'Listen to music and sing a song.',zh:'听音乐唱首歌。'},{en:'My hobby is reading books.',zh:'我的爱好是读书。'},{en:'Take a photo with my camera.',zh:'用我的相机拍张照片。'}]},
    18:{title:'Dreams and Future',sentences:[{en:'Follow your dream.',zh:'追寻你的梦想。'},{en:'The future is bright.',zh:'未来是光明的。'},{en:'Make a plan and try your best.',zh:'制定计划并全力以赴。'},{en:'Learn English every day and improve.',zh:'每天学英语，不断提高。'},{en:'Practice makes perfect.',zh:'熟能生巧。'},{en:'Be confident and achieve your dream!',zh:'自信一点，实现你的梦想！'},{en:'Life is beautiful.',zh:'生活是美好的。'}]}
  },
  categories:[
    {name:'传统文化',icon:'🎭',bg:'#fdf2f8',color:'#ec4899'},{name:'时事热点',icon:'📰',bg:'#eff6ff',color:'#3b82f6'},
    {name:'科技创新',icon:'💡',bg:'#fff7ed',color:'#f97316'},{name:'自然奥秘',icon:'🌍',bg:'#f0fdf4',color:'#10b981'},
    {name:'晨读美文',icon:'🌅',bg:'#fffbeb',color:'#f59e0b'},{name:'童话故事',icon:'🏰',bg:'#faf5ff',color:'#8b5cf6'},
    {name:'健康生活',icon:'❤️',bg:'#fff1f2',color:'#f43f5e'},{name:'更多',icon:'⋯',bg:'#f8fafc',color:'#64748b'}
  ],
};
